from pyspark.sql.types import Row
from pyspark.sql.types import *
import datetime
import os
import json


def load_expected_data(name, spark):
    root = os.path.dirname(__file__)
    path = os.path.join(root, "resources", "{}.json".format(name))
    with open(path) as f:
        d = json.load(f)
    return d


def make_telemetry_data():
    addons_expanded_sample = [
        Row(
            Submission_date=datetime.datetime(2019, 5, 15, 0, 0),
            client_id=u"9ad5490a-6fd8-47e8-9a1e-68e759d7f073",
            addon_id=u"fxmonitor@mozilla.org",
            blocklisted=False,
            name=u"Firefox Monitor",
            user_disabled=False,
            app_disabled=False,
            version=u"2.8",
            scope=1,
            type=u"extension",
            foreign_install=False,
            has_binary_components=False,
            install_day=17877,
            update_day=17877,
            signed_state=3,
            is_system=True,
            is_web_extension=True,
            multiprocess_compatible=True,
            os=u"Windows_NT",
            country=u"ES",
            subsession_length=3392,
            scalar_parent_browser_engagement_tab_open_event_count=15,
            places_pages_count=10,
            places_bookmarks_count=None,
            scalar_parent_browser_engagement_total_uri_count=220,
            devtools_toolbox_opened_count=None,
            active_ticks=395,
            histogram_parent_tracking_protection_enabled={0: 1, 1: 0},
            histogram_parent_webext_background_page_load_ms={
                1064: 3,
                1577: 0,
                964: 0,
                1429: 1,
                1174: 1,
            },
        ),
        Row(
            Submission_date=datetime.datetime(2019, 5, 1, 0, 0),
            client_id=u"9ad5490a-6fd8-47e8-9a1e-68e759d7f073",
            addon_id=u"webcompat-reporter@mozilla.org",
            blocklisted=False,
            name=u"WebCompat Reporter",
            user_disabled=False,
            app_disabled=False,
            version=u"1.1.0",
            scope=1,
            type=u"extension",
            oreign_install=False,
            has_binary_components=False,
            install_day=17850,
            update_day=17876,
            signed_state=None,
            is_system=True,
            is_web_extension=True,
            multiprocess_compatible=True,
            os=u"Windows_NT",
            country=u"ES",
            subsession_length=3392,
            places_pages_count=100,
            scalar_parent_browser_engagement_tab_open_event_count=12,
            places_bookmarks_count=None,
            scalar_parent_browser_engagement_total_uri_count=220,
            devtools_toolbox_opened_count=None,
            active_ticks=395,
            histogram_parent_tracking_protection_enabled={0: 1, 1: 0},
            histogram_parent_webext_background_page_load_ms={
                1064: 3,
                1577: 0,
                964: 0,
                1429: 1,
                1174: 1,
            },
        ),
        Row(
            Submission_date=datetime.datetime(2019, 1, 5, 0, 0),
            client_id=u"9ad5490a-6fd8-47e8-9a1e-68e759d7f073",
            addon_id=u"webcompat@mozilla.org",
            blocklisted=False,
            name=u"Web Compat",
            user_disabled=False,
            app_disabled=False,
            version=u"3.0.0",
            scope=1,
            type=u"extension",
            foreign_install=False,
            has_binary_components=False,
            install_day=17850,
            update_day=17876,
            signed_state=None,
            is_system=True,
            is_web_extension=True,
            multiprocess_compatible=True,
            places_pages_count=120,
            os=u"Windows_NT",
            country=u"ES",
            subsession_length=3392,
            scalar_parent_browser_engagement_tab_open_event_count=5,
            places_bookmarks_count=None,
            scalar_parent_browser_engagement_total_uri_count=220,
            devtools_toolbox_opened_count=None,
            active_ticks=395,
            histogram_parent_tracking_protection_enabled={0: 1, 1: 0},
            histogram_parent_webext_background_page_load_ms={
                1064: 3,
                1577: 0,
                964: 0,
                1429: 1,
                1174: 1,
            },
        ),
        Row(
            Submission_date=datetime.datetime(2019, 5, 1, 0, 0),
            client_id=u"9ad5490a-6fd8-47e8-9a1e-68e759d7f073",
            addon_id=u"screenshots@mozilla.org",
            blocklisted=False,
            name=u"Firefox Screenshots",
            user_disabled=False,
            app_disabled=False,
            version=u"35.0.0",
            scope=1,
            type=u"extension",
            foreign_install=False,
            has_binary_components=False,
            install_day=17850,
            update_day=17876,
            signed_state=None,
            is_system=True,
            is_web_extension=True,
            multiprocess_compatible=True,
            os=u"Windows_NT",
            country=u"ES",
            subsession_length=3392,
            places_pages_count=None,
            scalar_parent_browser_engagement_tab_open_event_count=None,
            places_bookmarks_count=None,
            scalar_parent_browser_engagement_total_uri_count=220,
            devtools_toolbox_opened_count=None,
            active_ticks=395,
            histogram_parent_tracking_protection_enabled={0: 1, 1: 0},
            histogram_parent_webext_background_page_load_ms={
                1064: 3,
                1577: 0,
                964: 0,
                1429: 1,
                1174: 1,
            },
        ),
        Row(
            Submission_date=datetime.datetime(2019, 1, 1, 0, 0),
            client_id=u"9ad5490a-6fd8-47e8-9a1e-68e759d7f073",
            addon_id=u"formautofill@mozilla.org",
            blocklisted=False,
            name=u"Form Autofill",
            user_disabled=False,
            app_disabled=False,
            version=u"1.0",
            scope=1,
            type=u"extension",
            foreign_install=False,
            has_binary_components=False,
            install_day=17850,
            update_day=17876,
            scalar_parent_browser_engagement_tab_open_event_count=None,
            signed_state=None,
            is_system=True,
            is_web_extension=True,
            multiprocess_compatible=True,
            os=u"Windows_NT",
            country=u"ES",
            subsession_length=3392,
            places_pages_count=10,
            places_bookmarks_count=5,
            scalar_parent_browser_engagement_total_uri_count=220,
            devtools_toolbox_opened_count=None,
            active_ticks=395,
            histogram_parent_tracking_protection_enabled={0: 1, 1: 0},
            histogram_parent_webext_background_page_load_ms={
                1064: 3,
                1577: 0,
                964: 0,
                1429: 1,
                1174: 1,
            },
        ),
    ]

    addons_schema = StructType(
        [
            StructField("Submission_date", TimestampType(), True),
            StructField("client_id", StringType(), True),
            StructField("addon_id", StringType(), True),
            StructField("blocklisted", BooleanType(), True),
            StructField("name", StringType(), True),
            StructField("user_disabled", BooleanType(), True),
            StructField("app_disabled", BooleanType(), True),
            StructField("version", StringType(), True),
            StructField("scope", IntegerType(), True),
            StructField("type", StringType(), True),
            StructField(
                "scalar_parent_browser_engagement_tab_open_event_count",
                IntegerType(),
                True,
            ),
            StructField("foreign_install", BooleanType(), True),
            StructField("has_binary_components", BooleanType(), True),
            StructField("install_day", IntegerType(), True),
            StructField("update_day", IntegerType(), True),
            StructField("signed_state", IntegerType(), True),
            StructField("is_system", BooleanType(), True),
            StructField("is_web_extension", BooleanType(), True),
            StructField("multiprocess_compatible", BooleanType(), True),
            StructField("os", StringType(), True),
            StructField("country", StringType(), True),
            StructField("subsession_length", LongType(), True),
            StructField("places_pages_count", IntegerType(), True),
            StructField("places_bookmarks_count", IntegerType(), True),
            StructField(
                "scalar_parent_browser_engagement_total_uri_count", IntegerType(), True
            ),
            StructField("devtools_toolbox_opened_count", IntegerType(), True),
            StructField("active_ticks", IntegerType(), True),
            StructField(
                "histogram_parent_tracking_protection_enabled",
                MapType(IntegerType(), IntegerType(), True),
                True,
            ),
            StructField(
                "histogram_parent_webext_background_page_load_ms",
                MapType(IntegerType(), IntegerType(), True),
                True,
            ),
        ]
    )

    return addons_expanded_sample, addons_schema


def make_fake_telemetry_data():
    addons_expanded_sample = [
        Row(
            Submission_date=datetime.datetime(2019, 5, 15, 0, 0),
            client_id=u"9ad5490a-6fd8-47e8-9a1e-68e759d7f073",
            addon_id=u"fxmonitor@mozilla.org",
            blocklisted=False,
            name=u"Firefox Monitor",
            user_disabled=False,
            app_disabled=False,
            version=u"2.8",
            scope=1,
            type=u"extension",
            foreign_install=False,
            has_binary_components=False,
            install_day=17877,
            update_day=17877,
            signed_state=3,
            is_system=True,
            is_web_extension=True,
            multiprocess_compatible=True,
            os=u"Windows_NT",
            country=u"ES",
            subsession_length=3392,
            scalar_parent_browser_engagement_tab_open_event_count=15,
            places_pages_count=10,
            places_bookmarks_count=None,
            scalar_parent_browser_engagement_total_uri_count=220,
            devtools_toolbox_opened_count=None,
            active_ticks=395,
            histogram_parent_tracking_protection_enabled={0: 1, 1: 0},
            histogram_parent_webext_background_page_load_ms={
                1064: 3,
                1577: 0,
                964: 0,
                1429: 1,
                1174: 1,
            },
        ),
        Row(
            Submission_date=datetime.datetime(2019, 5, 1, 0, 0),
            client_id=u"9ad5490a-6fd8-47e8-9a1e-68e759d7f073",
            addon_id=u"webcompat-reporter@mozilla.org",
            blocklisted=False,
            name=u"WebCompat Reporter",
            user_disabled=False,
            app_disabled=False,
            version=u"1.1.0",
            scope=1,
            type=u"extension",
            foreign_install=False,
            has_binary_components=False,
            install_day=17850,
            update_day=17876,
            signed_state=None,
            is_system=True,
            is_web_extension=True,
            multiprocess_compatible=True,
            os=u"Windows_NT",
            country=u"ES",
            subsession_length=3392,
            places_pages_count=100,
            scalar_parent_browser_engagement_tab_open_event_count=12,
            places_bookmarks_count=None,
            scalar_parent_browser_engagement_total_uri_count=220,
            devtools_toolbox_opened_count=None,
            active_ticks=395,
            histogram_parent_tracking_protection_enabled={0: 1, 1: 0},
            histogram_parent_webext_background_page_load_ms={
                1064: 3,
                1577: 0,
                964: 0,
                1429: 1,
                1174: 1,
            },
        ),
        Row(
            Submission_date=datetime.datetime(2019, 1, 5, 0, 0),
            client_id=u"9ad5490a-6fd8-47e8-9a1e-68e759d7f073",
            addon_id=u"webcompat@mozilla.org",
            blocklisted=False,
            name=u"Web Compat",
            user_disabled=False,
            app_disabled=False,
            version=u"3.0.0",
            scope=1,
            type=u"extension",
            foreign_install=False,
            has_binary_components=False,
            install_day=17850,
            update_day=17876,
            signed_state=None,
            is_system=True,
            is_web_extension=True,
            multiprocess_compatible=True,
            places_pages_count=120,
            os=u"Windows_NT",
            country=u"ES",
            subsession_length=3392,
            scalar_parent_browser_engagement_tab_open_event_count=5,
            places_bookmarks_count=None,
            scalar_parent_browser_engagement_total_uri_count=220,
            devtools_toolbox_opened_count=None,
            active_ticks=395,
            histogram_parent_tracking_protection_enabled={0: 1, 1: 0},
            histogram_parent_webext_background_page_load_ms={
                1064: 3,
                1577: 0,
                964: 0,
                1429: 1,
                1174: 1,
            },
        ),
        Row(
            Submission_date=datetime.datetime(2019, 5, 1, 0, 0),
            client_id=u"9ad5490a-6fd8-47e8-9a1e-68e759d7f073",
            addon_id=u"screenshots@mozilla.org",
            blocklisted=False,
            name=u"Firefox Screenshots",
            user_disabled=False,
            app_disabled=False,
            version=u"35.0.0",
            scope=1,
            type=u"extension",
            foreign_install=False,
            has_binary_components=False,
            install_day=17850,
            update_day=17876,
            signed_state=None,
            is_system=True,
            is_web_extension=True,
            multiprocess_compatible=True,
            os=u"Windows_NT",
            country=u"ES",
            subsession_length=3392,
            places_pages_count=None,
            scalar_parent_browser_engagement_tab_open_event_count=None,
            places_bookmarks_count=None,
            scalar_parent_browser_engagement_total_uri_count=220,
            devtools_toolbox_opened_count=None,
            active_ticks=395,
            histogram_parent_tracking_protection_enabled={0: 1, 1: 0},
            histogram_parent_webext_background_page_load_ms={
                1064: 3,
                1577: 0,
                964: 0,
                1429: 1,
                1174: 1,
            },
        ),
        Row(
            Submission_date=datetime.datetime(2019, 1, 1, 0, 0),
            client_id=u"9ad5490a-6fd8-47e8-9a1e-68e759d7f073",
            addon_id=u"formautofill@mozilla.org",
            blocklisted=False,
            name=u"Form Autofill",
            user_disabled=False,
            app_disabled=False,
            version=u"1.0",
            scope=1,
            type=u"extension",
            foreign_install=False,
            has_binary_components=False,
            install_day=17850,
            update_day=17876,
            scalar_parent_browser_engagement_tab_open_event_count=None,
            signed_state=None,
            is_system=True,
            is_web_extension=True,
            multiprocess_compatible=True,
            os=u"Windows_NT",
            country=u"ES",
            subsession_length=3392,
            places_pages_count=10,
            places_bookmarks_count=5,
            scalar_parent_browser_engagement_total_uri_count=220,
            devtools_toolbox_opened_count=None,
            active_ticks=395,
            histogram_parent_tracking_protection_enabled={0: 1, 1: 0},
            histogram_parent_webext_background_page_load_ms={
                1064: 3,
                1577: 0,
                964: 0,
                1429: 1,
                1174: 1,
            },
        ),
    ]

    addons_schema = StructType(
        [
            StructField("Submission_date", TimestampType(), True),
            StructField("client_id", StringType(), True),
            StructField("addon_id", StringType(), True),
            StructField("blocklisted", BooleanType(), True),
            StructField("name", StringType(), True),
            StructField("user_disabled", BooleanType(), True),
            StructField("app_disabled", BooleanType(), True),
            StructField("version", StringType(), True),
            StructField("scope", IntegerType(), True),
            StructField("type", StringType(), True),
            StructField(
                "scalar_parent_browser_engagement_tab_open_event_count",
                IntegerType(),
                True,
            ),
            StructField("foreign_install", BooleanType(), True),
            StructField("has_binary_components", BooleanType(), True),
            StructField("install_day", IntegerType(), True),
            StructField("update_day", IntegerType(), True),
            StructField("signed_state", IntegerType(), True),
            StructField("is_system", BooleanType(), True),
            StructField("is_web_extension", BooleanType(), True),
            StructField("multiprocess_compatible", BooleanType(), True),
            StructField("os", StringType(), True),
            StructField("country", StringType(), True),
            StructField("subsession_length", LongType(), True),
            StructField("places_pages_count", IntegerType(), True),
            StructField("places_bookmarks_count", IntegerType(), True),
            StructField(
                "scalar_parent_browser_engagement_total_uri_count", IntegerType(), True
            ),
            StructField("devtools_toolbox_opened_count", IntegerType(), True),
            StructField("active_ticks", IntegerType(), True),
            StructField(
                "histogram_parent_tracking_protection_enabled",
                MapType(IntegerType(), IntegerType(), True),
                True,
            ),
            StructField(
                "histogram_parent_webext_background_page_load_ms",
                MapType(IntegerType(), IntegerType(), True),
                True,
            ),
        ]
    )

    return addons_expanded_sample, addons_schema


def main_summary_for_user_engagement():
    schema = StructType(
        [
            StructField("disabled_addons_ids", ArrayType(StringType(), True), True),
            StructField("client_id", StringType(), True),
        ]
    )
    rows = [
        Row(
            disabled_addons_ids=[u"{972ce4c6-7e08-4474-a285-3208198ce6fd}"],
            client_id=u"64e478a9-7205-bd48-af6c-49a8c4bbdba9",
        ),
        Row(
            disabled_addons_ids=[u"{972ce4c6-7e08-4474-a285-3208198ce6fd}"],
            client_id=u"94938cbb-2f0f-eb48-ab1c-c04c9c72f95d",
        ),
        Row(
            disabled_addons_ids=[u"{972ce4c6-7e08-4474-a285-3208198ce6fd}"],
            client_id=u"c743166e-62dc-4a04-b6ca-5dfbca18c753",
        ),
        Row(
            disabled_addons_ids=[
                u"383882@modext.tech",
                u"firefox@getpocket.com",
                u"{972ce4c6-7e08-4474-a285-3208198ce6fd}",
            ],
            client_id=u"1c8d8ba3-0b53-42c6-a513-2b2830d03a8c",
        ),
        Row(
            disabled_addons_ids=[
                u"ca@dictionaries.addons.mozilla.org",
                u"en-GB@dictionaries.addons.mozilla.org",
                u"es-es@dictionaries.addons.mozilla.org",
                u"{972ce4c6-7e08-4474-a285-3208198ce6fd}",
                u"{CAFEEFAC-0016-0000-0039-ABCDEFFEDCBA}",
            ],
            client_id=u"4410aad2-8c7d-4806-97d9-1d6ec75b9085",
        ),
    ]
    return rows, schema


def make_search_daily_data():
    search_daily_sample = [
        Row(
            client_id=u"9bcc2356-f241-4a57-bd51-78bab300312f",
            Submission_date=datetime.datetime(2019, 4, 14, 0, 0),
            sap=3,
            tagged_sap=None,
            organic=6,
        ),
        Row(
            client_id=u"c3ef033b-d436-4dd8-84c8-95bbb1eafcca",
            Submission_date=datetime.datetime(2019, 4, 14, 0, 0),
            sap=1,
            tagged_sap=6,
            organic=None,
        ),
        Row(
            client_id=u"734ccbab-cc80-6d40-b4b4-c1de28ee6f44",
            Submission_date=datetime.datetime(2019, 4, 14, 0, 0),
            sap=1,
            tagged_sap=None,
            organic=1,
        ),
        Row(
            client_id=u"13e24161-85b7-4c1e-98e6-b58b64481bd2",
            Submission_date=datetime.datetime(2019, 4, 14, 0, 0),
            sap=7,
            tagged_sap=10,
            organic=None,
        ),
        Row(
            client_id=u"f5a03324-1c16-4143-88fa-f4306f6d2359",
            Submission_date=datetime.datetime(2019, 4, 14, 0, 0),
            sap=1,
            tagged_sap=None,
            organic=8,
        ),
    ]

    search_daily_schema = StructType(
        [
            StructField("client_id", StringType(), True),
            StructField("Submission_date", TimestampType(), True),
            StructField("sap", IntegerType(), True),
            StructField("tagged_sap", IntegerType(), True),
            StructField("organic", IntegerType(), True),
        ]
    )

    return search_daily_sample, search_daily_schema
